services:
  db:
    image: postgres:latest
    container_name: mi-postgres
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: stuky-api
    env_file:
      - .env.api
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: